### ISSUE TITLE
Hinzufügen von Funktionalitäten der Kartendarstellung auf der Startseite

### ISSUE THREAD

**Issue by Jonasstemme** [vitrum-connect/5gla-react-visualization#2]
**Beschreibung**
Als Nutzer möchte ich, dass auf der Startseite die Visualisierungslinien und Sensoren auf der Karte dargestellt werden, damit ich die relevanten Bereiche und Sensoren leicht erkennen kann.

**Akzeptanzkriterien**

Die User Story gilt als erfolgreich umgesetzt, wenn:

- ~~ein Geoserver aufgesetzt und konfiguriert wurde,~~
- Visualisierungslinien der Schläge angezeigt werden,
- Die Karte so gezoomt ist, dass die Visualisierungslinien sichtbar sind.
- Die Sensoren durch Pins auf der Karte dargestellt werden.

![Image](https://github.com/user-attachments/assets/f730b8d8-cfbf-4baa-8c17-41fb13929046)

**Schätzung 8 h**
Annahme ohne Tennant Logik (Kann später ergänz werden)

**Comment by THS-LMIS** [comment]
Wie im Daily besprochen, soll die Kartendarstellung über Open Street Map und nicht über den GeoServer realisiert werden.
