### ISSUE TITLE
Einbinden der Gruppen auf der Startseite inkl. Implementierung der Single Selection Auswahl

### ISSUE THREAD

**Issue by Jonasstemme** [vitrum-connect/5gla-react-visualization#3]
**Beschreibung**
Als Nutzer möchte ich auf der Startseite eine Auswahl der Gruppen sehen und die Möglichkeit haben, einen einzelne Gruppe auszuwählen, um gezielt mit einem bestimmten Bereich arbeiten zu können.

**Akzeptanzkriterien**

Die User Story gilt als erfolgreich umgesetzt, wenn:

- Auf der linken Seite der Startseite eine Überschrift mit dem Titel „Auswahl der Gruppen angezeigt wird.
- Sämtliche Gruppen in einer Liste dargestellt werden.
- Eine Single Selection-Auswahl (Radio-Button) implementiert wurde, die es ermöglicht, dass der Nutzer nur eine Gruppe auswählen kann.
- die Gruppen werden anhand des FIWARE-Service-Path abgefragt (siehe https://fiware-orion.readthedocs.io/en/1.4.0/user/service_path/index.html)

![Image](https://github.com/user-attachments/assets/ab9ea23c-4fcf-4af1-9ec7-f5562f8dc89e)

**Schätzung 10 h**

**Comment by Jonasstemme** [comment]
@saschadoemer: Fragestellungen

**Zugang zum System:**
- Kannst du uns Verbindungsdaten (URL) für den NGSI-Proxy zur Verfügung stellen?
- Wie kommen wir auf den Server (Zugangsdaten? / Benötigen wir einen VPN?)

**Abfrage der Daten:**
- Wie muss eine Anfrage an den NGSI-Proxy aussehen?

**Datenstruktur:**
- Gibt es eine Dokumentation über die derzeitige Datenstruktur?
- In welchem Format kommen die Daten aus dem NGSI-Proxy?

**Weiterführende Aufgabe:** 
- Bereitstellung einer Liste mit sämtlichen Gruppen die angelegt wurden.
- Für jede Gruppe sollten die entsprechenden Polygone mit übergeben werden.

**Comment by saschadoemer** [comment]
Klar, kann ich machen:

URL über Mattermost, da keine Zugangsdaten und kein VPN notwendig.

Die Abfrage der Daten werden als Entitäten direkt via API abgefragt, siehe auch hier: https://fiwaretourguide.readthedocs.io/en/latest/core/ngsi-v2/how-to-update-and-query-context-information

Eine direkte Abfrage der Service-Path-Einträge ist nicht machbar, ich kann aber eine Schnittstelle per REST bereitstellen, die diese beinhaltet. Das Format der Daten ist JSON, NGSI-spezifisch. Ich kann die Daten aber auch direkt via REST liefern.

**Comment by saschadoemer** [comment]
Hier noch einmal kurz die Referenz zum entsprechenden Tonic bei StackOverflow. Bitte entscheidet und definiert, welche Schnittstelle ihr braucht.

https://stackoverflow.com/questions/43054881/get-all-fiware-servicepath-for-a-specific-fiware-service

Wenn wir allerdings über eine Custom-Schnittstelle gehen, dann haben wir das Problem, dass wir nicht mehr nur via Context-Broker arbeiten.

@Jonasstemme was ist mit Polygonen gemeint? Wenn das die Schläge sind, dann sind die ebenfalls über eine eigene Entität aus FIWARE abfragbar (sofern jemand welche angelegt hat).

**Comment by saschadoemer** [comment]
Im Daily mit @Vitrum-LL abgestimmt, dass die Abfrage per REST-API in Ordnung ist.
