### ISSUE TITLE
Anlegen einer Subsite mit dem Titel des entsprechenden Gruppennamens

### ISSUE THREAD

**Issue by Jonasstemme** [vitrum-connect/5gla-react-visualization#4]
Beschreibung 
Als Nutzer möchte ich eine Subsite aufrufen können, um eine Übersicht über die Gruppenteilnehmer zu erhalten.

Akzeptanzkriterien

Die User Story gilt als erfolgreich umgesetzt, wenn:

-     Ein "Weiter"-Button auf der Startseite implementiert wurde, der zur Subsite führt.
-     Eine Subsite angelegt wurde.
-     Eine Überschrift auf der Seite erscheint mit dem Titel "Übersicht der Gruppeninhalte".
-     Sämtliche Gruppenteilnehmer in einer Liste angezeigt werden.
-     Die Liste sollte als Single-Selection (Radio-Button) aufgebaut werden.
-     Sobald ein Sensor ausgewählt wurde, soll dieser farblich gekennzeichnet werden.
-     Ein Button zum Zurücknavigieren implementiert wurde.
-     Das Impressum im Footer eingebunden ist.
-     Der Gruppenname sollte oben angezeigt werden,

![Image](https://github.com/user-attachments/assets/b6ee5ecd-62ff-404a-b3f2-71bddbad0810)

**Schätzung 9 h**

**Comment by THS-LMIS** [comment]
Es werden Radiobuttons statt Checkboxen benutzt, da immer eine Auswahl erlaubt ist.

**Comment by Jonasstemme** [comment]
@saschadoemer: Bereitstellung einer API:

Anfrage beim NGSI-Proxy: Erfolgt durch Thomas
- Soll das auch als FIWARE-Service-Path erfolgen oder sollten an dieser Stelle nur Parameter (Username / Gruppenauswahl) übergeben werden?

Antwort des NGSI-Proxy:
- Liste der Gruppeninhalte
- Koordinaten der jeweiligen Bodenfeuchtigkeitssensoren

**Comment by Jonasstemme** [comment]
- Anpassung der Navigation (Breadcrump)
- Hinzufügen eines Buttons, damit die Auswahl aufgehoben wird
- Analyse der Namenslogik
- Visuelle Darstellung der ausgewählten Sensoren und ggf. Schläge
